### ISSUE TITLE
Compliance with PSR-7 : HTTP message interfaces

### ISSUE THREAD

**Issue by jaoued** [sylouuu/php-curl#3]
Hi,

Because they are a new standard defined by [PHP Framework Interop Group](http://www.php-fig.org/psr/psr-7/) to handle HTTP request and response messages, it would be interresting to update your package to make it compatible with PSR-7 standard.

Regards.

**Comment by sylouuu** [comment]
Hi,

The `php-curl` project just wants to be "lightweight". There is no point to be PSR-7 compliant.

You may consider [Guzzle](https://github.com/guzzle/guzzle), my goal isn't to create a clone of [Guzzle](https://github.com/guzzle/guzzle) but to offer another solution for common standard needs.

Regards
