### ISSUE TITLE
Proposal: Add `query` option for GET method to build query automatically

### ISSUE THREAD

**Issue by chez14** [sylouuu/php-curl#4]
On your [`$options` constructor](https://github.com/sylouuu/php-curl#constructor-options), the `data` is available just for `Post`, `Put` and `Patch`.

I'd like to have a new option to supply queries by giving an array, just like `data` did.

Thanks!

**Comment by sylouuu** [comment]
Hi @chez14 

This package is not up-tu-date. To achieve this you have to do something like;

```php
$request = new Curl\Get('http://domain.com?' . http_build_query(['foo' => 'bar]));
```

I suggest you to use a popular package like: https://github.com/guzzle/guzzle

Best

**Comment by chez14** [comment]
Ahh ok ok... i'm still using this repo for several project as it is really light and easy to use, are you going to leave the project as is?

I can help maintaining this repo btw :wink:
